version: "3.3"

services:
    api:
        image: hausmilbe/todo_api:development
        ports:
            - "9082:80"
        environment:
            MONGO_DB_URL: "mongo"
            MONGO_DB_PORT: "27017"
            MONGO_DB_NAME: "todo_dev_database"
        depends_on:
            - mongo
    webui:
        image: hausmilbe/todo_webui:development
        ports:
            - "8082:80"
    mongo:
        image: "mongo:latest"
