version: "3.3"

services:
    api:
        build:
            context: todo_api/
            dockerfile: todo_api.configfile
    webui:
        build:
            context: todo_webui/
            dockerfile: todo_webui.configfile
        depends_on:
            - api
