version: "3.3"

services:
    api:
        ports:
            - "9082:80"
        environment:
            MONGO_DB_URL: "mongo"
            MONGO_DB_PORT: "27017"
            MONGO_DB_NAME: "todo_dev_database"
        depends_on:
            - mongo
    mongo:
        image: "mongo:latest"
