version: "3.3"

services:
    api:
        build:
            context: todo_api/
            dockerfile: todo_api.containerfile
    webui:
        build:
            context: todo_webui/
            dockerfile: todo_webui.containerfile
        depends_on:
            - api
