version: "3.3"

services:
    api:
        image: hausmilbe/todo_api:latest
        ports:
            - "9080:80"
        environment:
            MONGO_DB_URL: "raspiserver"
            MONGO_DB_PORT: "27017"
            MONGO_DB_NAME: "todo_prod_database"
    webui:
        image: hausmilbe/todo_webui:latest
        ports:
            - "8080:80"
